# Generated by Django 5.2.3 on 2026-03-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_make_service_price_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='county',
            field=models.CharField(blank=True, help_text='County/area where this service operates (for transporters)', max_length=100, null=True),
        ),
    ]
