# Generated by Django 5.2.3 on 2025-07-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_referral_order_remove_product_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Affiliate'), ('vendor', 'Vendor'), ('admin', 'Admin'), ('customer', 'Customer')], default='user', max_length=20),
        ),
    ]
