# Generated by Django 5.2.3 on 2025-09-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('affiliate', 'Affiliate'), ('vendor', 'Vendor'), ('admin', 'Admin'), ('customer', 'Customer')], default='user', max_length=20),
        ),
    ]
