# Generated by Django 5.2.3 on 2025-10-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Affiliate'), ('vendor', 'Vendor'), ('admin', 'Admin'), ('customer', 'Customer')], default='user', max_length=20),
        ),
    ]
