# Generated by Django 5.2.3 on 2025-10-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_certificate_number_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
