# Generated by Django 5.2.3 on 2025-11-15 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_vendor_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_certificate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
