# Generated by Django 5.2.3 on 2025-12-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_affiliatecertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vendor_type',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('wholesaler', 'Wholesaler'), ('transporter', 'Transporter'), ('retailer', 'Retailer')], max_length=20, null=True),
        ),
    ]
