# Generated by Django 5.2.3 on 2026-01-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_vendor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='service_provider_type',
            field=models.CharField(blank=True, choices=[('veterinary', 'Veterinary Services'), ('transport', 'Transporter'), ('storage', 'Storage provider')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Affiliate'), ('vendor', 'Vendor'), ('admin', 'Admin'), ('customer', 'Customer'), ('service_provider', 'Service Provider')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vendor_type',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer')], max_length=20, null=True),
        ),
    ]
