# Generated by Django 5.2.3 on 2026-02-27 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customuser_service_provider_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('m-pesa', 'M-Pesa'), ('airtel-money', 'Airtel Money')], default='m-pesa', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mpesa_number',
            field=models.CharField(blank=True, help_text='Required for vendors to receive payments.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registered_by_affiliate',
            field=models.ForeignKey(blank=True, help_text='The affiliate who referred this user, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_fee_amount',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_paid',
            field=models.BooleanField(default=False, help_text='Indicates if the vendor has paid the registration fee.'),
        ),
        migrations.CreateModel(
            name='VendorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('company_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('affiliate_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('phone', models.CharField(help_text='Phone used for payment', max_length=15)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed')], default='pending', max_length=20)),
                ('company_paid', models.BooleanField(default=False, help_text='Company received payment')),
                ('affiliate_paid', models.BooleanField(default=False, help_text='Affiliate received commission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('affiliate', models.ForeignKey(blank=True, help_text='Affiliate who gets 50% commission', limit_choices_to={'role': 'affiliate'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_registrations', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.OneToOneField(limit_choices_to={'role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Registration',
                'verbose_name_plural': 'Vendor Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationPaymentSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('company', 'Company'), ('affiliate', 'Affiliate')], max_length=20)),
                ('recipient_phone', models.CharField(blank=True, max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('mpesa_conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('mpesa_response_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('recipient', models.ForeignKey(blank=True, help_text='Null for company', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='users.vendorregistration')),
            ],
            options={
                'verbose_name': 'Registration Payment Split',
                'verbose_name_plural': 'Registration Payment Splits',
                'ordering': ['-created_at'],
            },
        ),
    ]
