# Generated by Django 5.2.3 on 2026-03-01 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_mobile_money_provider_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorregistration',
            options={},
        ),
        migrations.RenameField(
            model_name='vendorregistration',
            old_name='checkout_request_id',
            new_name='paystack_reference',
        ),
        migrations.RenameField(
            model_name='vendorregistration',
            old_name='merchant_request_id',
            new_name='paystack_transaction_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_money_provider',
        ),
        migrations.RemoveField(
            model_name='vendorregistration',
            name='affiliate_paid',
        ),
        migrations.RemoveField(
            model_name='vendorregistration',
            name='company_paid',
        ),
        migrations.RemoveField(
            model_name='vendorregistration',
            name='mpesa_receipt_number',
        ),
        migrations.RemoveField(
            model_name='vendorregistration',
            name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='paystack_subaccount_code',
            field=models.CharField(blank=True, help_text='Paystack subaccount code for vendors to receive payments.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorregistration',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorregistration',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RegistrationPaymentSplit',
        ),
    ]
