# Generated by Django 5.2.3 on 2026-03-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_vendorregistration_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mpesa_number',
        ),
    ]
