# Generated by Django 5.2.3 on 2026-02-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total paid by customer', max_digits=10, null=True),
        ),
    ]
