# Generated by Django 5.2.3 on 2026-03-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsplit',
            name='recipient_phone',
            field=models.CharField(blank=True, help_text='M-Pesa phone number', max_length=15),
        ),
    ]
