# Generated by Django 5.2.3 on 2026-03-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_missing_order_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='affiliate_paid',
            field=models.BooleanField(default=False, help_text='Affiliate received M-Pesa payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vendor_paid',
            field=models.BooleanField(default=False, help_text='Vendor received M-Pesa payment'),
        ),
    ]
