# Generated by Django 5.2.3 on 2026-03-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_updated_at_alter_order_affiliate_paid_and_more'),
        ('orders', '0007_remove_order_updated_at'),
    ]

    operations = [
    ]
