# Generated by Django 5.2.3 on 2026-03-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_paymentsplit_mpesa_conversation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsplit',
            name='mpesa_conversation_id',
        ),
        migrations.RemoveField(
            model_name='paymentsplit',
            name='mpesa_originator_conversation_id',
        ),
        migrations.RemoveField(
            model_name='paymentsplit',
            name='mpesa_response_code',
        ),
        migrations.RemoveField(
            model_name='paymentsplit',
            name='mpesa_response_description',
        ),
        migrations.RemoveField(
            model_name='paymentsplit',
            name='mpesa_transaction_id',
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='paystack_reference',
            field=models.CharField(blank=True, help_text='Paystack reference for company payment', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='affiliate_paid',
            field=models.BooleanField(default=False, help_text='Affiliate received M-Pesa payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vendor_paid',
            field=models.BooleanField(default=False, help_text='Vendor received M-Pesa payment'),
        ),
    ]
