# Generated by Django 5.2.3 on 2026-03-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_paymentsplit_mpesa_conversation_id_and_more'),
        ('orders', '0009_fix_referral_columns'),
    ]

    operations = [
    ]
