from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_merge_20260307_1624'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS orders_paymentsplit (
                id bigint generated by default as identity primary key,
                recipient_type varchar(20) NOT NULL,
                recipient_phone varchar(15) NOT NULL DEFAULT '',
                amount numeric(10,2) NOT NULL,
                status varchar(20) NOT NULL DEFAULT 'pending',
                paystack_reference varchar(100),
                created_at timestamptz NOT NULL DEFAULT now(),
                processed_at timestamptz,
                completed_at timestamptz,
                retry_count integer NOT NULL DEFAULT 0,
                max_retries integer NOT NULL DEFAULT 3,
                order_id bigint NOT NULL REFERENCES orders_order(id) DEFERRABLE INITIALLY DEFERRED,
                recipient_id bigint REFERENCES users_customuser(id) DEFERRABLE INITIALLY DEFERRED
            );

            CREATE TABLE IF NOT EXISTS orders_vendorpayout (
                id bigint generated by default as identity primary key,
                amount numeric(10,2) NOT NULL,
                is_paid boolean NOT NULL DEFAULT false,
                paid_at timestamptz,
                created_at timestamptz NOT NULL DEFAULT now(),
                order_id bigint NOT NULL REFERENCES orders_order(id) DEFERRABLE INITIALLY DEFERRED,
                payment_split_id bigint REFERENCES orders_paymentsplit(id) DEFERRABLE INITIALLY DEFERRED,
                vendor_id bigint NOT NULL REFERENCES users_customuser(id) DEFERRABLE INITIALLY DEFERRED
            );
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS orders_vendorpayout;
            DROP TABLE IF EXISTS orders_paymentsplit;
            """
        ),
    ]