# Generated by Django 5.2.3 on 2026-03-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_create_missing_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsplit',
            name='paystack_reference',
            field=models.CharField(blank=True, help_text='Paystack reference for company payment', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='affiliate_paid',
            field=models.BooleanField(default=False, help_text='Affiliate received M-Pesa payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vendor_paid',
            field=models.BooleanField(default=False, help_text='Vendor received M-Pesa payment'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Commission percentage (default 5%)', max_digits=5),
        ),
    ]
