# Generated by Django 5.2.3 on 2026-03-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_paymentsplit_mpesa_conversation_id_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE orders_paymentsplit DROP COLUMN IF EXISTS mpesa_conversation_id;",
            reverse_sql="SELECT 1;"
        ),
        migrations.RunSQL(
            "ALTER TABLE orders_paymentsplit DROP COLUMN IF EXISTS mpesa_originator_conversation_id;",
            reverse_sql="SELECT 1;"
        ),
        migrations.RunSQL(
            "ALTER TABLE orders_paymentsplit DROP COLUMN IF EXISTS mpesa_response_code;",
            reverse_sql="SELECT 1;"
        ),
        migrations.RunSQL(
            "ALTER TABLE orders_paymentsplit DROP COLUMN IF EXISTS mpesa_response_description;",
            reverse_sql="SELECT 1;"
        ),
        migrations.RunSQL(
            "ALTER TABLE orders_paymentsplit DROP COLUMN IF EXISTS mpesa_transaction_id;",
            reverse_sql="SELECT 1;"
        ),
    ]