# Generated by Django 5.2.3 on 2026-03-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_paymentsplit_mpesa_conversation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsplit',
            name='mpesa_conversation_id',
        ),
        migrations.RemoveField(
            model_name='paymentsplit',
            name='mpesa_originator_conversation_id',
        ),
        migrations.RemoveField(
            model_name='paymentsplit',
            name='mpesa_response_code',
        ),
        migrations.RemoveField(
            model_name='paymentsplit',
            name='mpesa_response_description',
        ),
        migrations.RemoveField(
            model_name='paymentsplit',
            name='mpesa_transaction_id',
        ),
    ]
