# Generated by Django 5.2.3 on 2026-03-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_guest_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
