# Generated by Django 5.2.3 on 2026-03-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_guest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='goods_description',
            field=models.TextField(blank=True, help_text="Buyer's description of goods (farm products only)", null=True),
        ),
    ]
