# Generated by Django 5.2.3 on 2025-12-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='farmer_price',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_kg',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='retailer_price',
            field=models.DecimalField(decimal_places=2, default=600, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='visible_to',
            field=models.CharField(choices=[('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('consumers', 'Consumers')], default='consumers', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesaler_price',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10),
            preserve_default=False,
        ),
    ]
